name: Auto Sign-in for BBS

on:
  schedule:
    - cron: '10 23 * * *'
  workflow_dispatch:

jobs:
  sign_in_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          pip install playwright
          pip install git+https://github.com/qqhsx/my-utils.git

      # 安装 Chromium 浏览器及其系统依赖
      - name: Install Playwright Browsers
        run: |
          playwright install --with-deps chromium

      - name: Run sign-in script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          IKUUU_DOMAIN: ${{ secrets.IKUUU_DOMAIN }}
          WX_CORPID: ${{ secrets.WX_CORPID }}
          WX_CORPSECRET: ${{ secrets.WX_CORPSECRET }}
          WX_AGENTID: ${{ secrets.WX_AGENTID }}
          WX_WEBHOOK: ${{ secrets.WX_WEBHOOK }}
        run: python sign_ikuuu.py
